mysql_root_password: "codeby"
mysql_databases:
  - name: wordpress
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
mysql_users:
  - name: wordpress
    host: localhost
    password: "codeby"
    priv: "wordpress.*:ALL"
