apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Values.namespace }}
data:
  wp-config.php: |
    define('WP_TABLE_PREFIX', '{{ .Values.wordpress.config.tablePrefix }}');